-- FinTrack Supabase Schema
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/tsefcgjifoppyssavppv/sql/new)

-- 1. Table for storing user progress (FinanceState)
create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

-- 2. Index for fast lookup by user_id
create index if not exists idx_user_progress_user_id on public.user_progress (user_id);

-- 3. Enable Row Level Security
alter table public.user_progress enable row level security;

-- 4. Policy: users can only read their own data
create policy "Users can read own progress"
  on public.user_progress
  for select
  using (auth.uid() = user_id);

-- 5. Policy: users can only insert their own data
create policy "Users can insert own progress"
  on public.user_progress
  for insert
  with check (auth.uid() = user_id);

-- 6. Policy: users can only update their own data
create policy "Users can update own progress"
  on public.user_progress
  for update
  using (auth.uid() = user_id);

-- 7. Policy: users can only delete their own data
create policy "Users can delete own progress"
  on public.user_progress
  for delete
  using (auth.uid() = user_id);
